Create docs aug2023
openhwgroup/core-v-mcu-devkit pull request #25
Opened 2023-08-16 02:22 UTC by DBees

2023-08-16 17:33 UTC, MikeOpenHWGroup requested changes
A few formatting comments.  Also, you'll need a `readthedocs.yaml` at the top-level if you plan to use RTD to publish these docs on the web with RTD.

2023-08-16 17:33 UTC, MikeOpenHWGroup commented on docs/doc-src/software-description.rst
> +  Copyright (c) 2023 OpenHW Group
Dito.

2023-08-17 00:55 UTC, DBees commented on docs/README.md
> +requirements in `../python-requirements.txt`).
guilty

2023-08-17 01:26 UTC, DBees commented
@MikeOpenHWGroup thanks for the comments. I've corrected these and a few other things also.

2023-08-17 14:08 UTC, MikeOpenHWGroup commented
> @MikeOpenHWGroup thanks for the comments. I've corrected these and a few other things also.

Yep, saw that.  The updates look good.  A couple things still outstanding:
1. The path to the requirements file in `docs/README.md` needs to be fixed.
2. We should also add the `build.os` statements to the `.readthedocs.yaml` file (in your defence, we heard about this from RTD _after_ you opened this PR).

2023-08-17 20:19 UTC, DBees commented
@MikeOpenHWGroup should be clean now

2023-08-17 20:20 UTC, merged